### ISSUE TITLE
Console install throws error on mysql database creation. Needs a better error message

### ISSUE THREAD

**Issue by evert** [fruux/sabre-katana#218] opened 2015-05-18 08:17 UTC
Steps:

1. Run `./bin/katana install`.
2. Answer all the questions.

```
Choose the database driver (sqlite or mysql) [default: sqlite]: mysql
Choose MySQL host: localhost
Choose MySQL port [default: 3306]:
Choose MySQL database name: katana
Choose MySQL username: root
Choose MySQL password:

Ready to install? (Enter to continue, Ctrl-C to abort)


Create configuration file…
Configuration file created 👍!
Create the database…
An error occured: Cannot create the database.
```

This error is thrown because the database does not exist and the installation script does not create it. The error message should be modified to make this more clear to the user, as I didn't realize it =)

**Comment by Hywan** [comment] 2015-05-18 08:51
And?

**Comment by Hywan** [comment] 2015-05-18 08:53
Hmm, tried locally, I can reproduce. Very strange.

**Comment by evert** [comment] 2015-05-18 08:56
I assume that exceptions are being caught. Is it possible to make it more verbose so I can see and paste the real underlying exceptions?

**Comment by Hywan** [comment] 2015-05-18 08:58
Hmm, yup. The issue is that the database does not exist (katana does not create the database for us).

**Comment by evert** [comment] 2015-05-18 08:58
Ahh! In that case it should at least be a UX issue =)

**Comment by evert** [comment] 2015-05-18 08:58
Changing the title of the ticket

**Comment by Hywan** [comment] 2015-05-18 08:59
And also `localhost` is not valid for MySQL. Most of the time, it is `127.0.0.1`.

**Comment by evert** [comment] 2015-05-18 09:00
localhost works here and is actually faster because it uses a unix socket instead of going through the network stack.

**Comment by Hywan** [comment] 2015-05-18 09:01
Not here. But anyway, I can't log the administrator panel… I don't understand why.

**Comment by Hywan** [comment] 2015-05-18 09:17
Ok, previous comment fixed by #221.

**Comment by Hywan** [comment] 2015-05-18 09:19
Well, I would say that the “Cannot create the database” is verbose enough ;-). But yes, let's go for a little more detailed message.

**Comment by evert** [comment] 2015-05-18 09:22
@Hywan well, when I read 'Cannot create the database' I think: it's trying to run `CREATE DATABASE` and it fails, so it's an incorrect message altogether for people used to using MySQL.

Usually I would say that showing the real underlying exception is a much better idea _unless_ we know exactly what the exception is and we can show a more user-friendly message. In this case it looks like it was more like a catch-all, which I think is less useful than the real error message. I just know it fails but I don't know why or how to solve this problem.

**Comment by Hywan** [comment] 2015-05-18 09:22
Yup yup exactly ;-).

**Comment by Hywan** [comment] 2015-05-18 09:23
Actually, we do have the exception: https://github.com/fruux/sabre-katana/blob/master/lib/Server/Installer.php#L391-L396. We just need to print it.

**Closed** 2015-05-18 10:01 UTC
Labels: bug, component bin, component install
