### ISSUE TITLE
An error occured: fstat() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by controlcde** [fruux/sabre-katana#287] opened 2015-07-13 07:02 UTC
On a fresh installation (0.3.2) on debian jessie with apache2.4 I get the error
> An error occured: fstat() expects parameter 1 to be resource, boolean given

after clicking "install" on admin account creation with sqlite. Browser is FF39.0.

**Comment by controlcde** [comment] 2015-07-13 07:06
more details on exceptions.log:
> "fstat() expects parameter 1 to be resource, boolean given" vendor/hoa/core/Protocol.php:843

**Comment by Hywan** [comment] 2015-07-13 07:32
Duplicate of #277.

**Closed by Hywan** 2015-07-13 07:32 UTC
